### ISSUE TITLE
Errors with "runCaSpER" function

### ISSUE THREAD

**Issue by dstueckm** [akdess/CaSpER#9]
Hello,

I've been trying to use your package on some single-cell data but have been running into an issue. I've gotten to the point where I have successfully created a Casper Object using the following command:

`co <- CreateCasperObject(raw.data=log.ge,loh.name.mapping=loh.name.mapping, sequencing.type="single-cell", 
                             cnv.scale=3, loh.scale=3, 
                             expr.cutoff=0.1, 
                             annotation=annotation, loh=loh, method = "iterative", 
                             control.sample.ids=control, cytoband=cytoband, 
                             genomeVersion = "hg38", log.transformed = TRUE)`

When I then try to use the function "runCaSpER", I get an error regardless of the method chosen. With

`final.co <- runCaSpER(co)`

I get

> Performing recursive median filtering...
Error in maf_temp[which(as.character(maf_temp$chr) == as.character(m)),  : 
  incorrect number of dimensions

And with

`final.co <- runCaSpER(co, method = "fixed")`

I get

> Error in manualSegment(correctOut$copy, chr, autosomes, param, maxiter,  : 
  Length of inputs do not match for one of: copy, chr, autosomes

I can't tell what the problem is from there error messages, do you have any ideas?

Thanks in advance

**Comment by akdess** [comment]
Hi  @dstueckm, Is chr column in maf, chr1, chr2, ...chr22? It should be 1, 2, 3, ...22. We should update the code to make it compatible. Thanks a lot for letting us know!

**Comment by akdess** [comment]
final.co <- runCaSpER(co, method = "fixed") error might be related to deprecated IRanges package. I have updated the code. 
Thanks!

**Comment by dstueckm** [comment]
Thanks for the quick response! I tried ordering the chromosome identifiers in loh, centromere, annotation, and co@cytoband, and I'm still getting the same error message. The code I used to order these was

`loh[[1]][[1]]$chr <- factor(loh[[1]][[1]]$chr, levels = c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","X","Y"))`

`loh[[1]][[1]][order(loh[[1]][[1]]$chr), ]`

EDIT: if your concern was about the names themselves rather than the order, only my "centromere" object had chromosome names in the form "chr#", and I had previously converted those to numbers with gsub()

**Comment by akdess** [comment]
Hi @dstueckm, can you share your R object with me akdess [at] gmail. com ? I will be more helpful if I can see the data. Thanks!

**Comment by Josephinedh** [comment]
Hi,

I get the same error when trying to run runCaSpER, also when I use the dataset from the 10x data tutorial.

> Error in manualSegment(correctOut$copy, chr, autosomes, param, maxiter, :
> Length of inputs do not match for one of: copy, chr, autosomes

In addition I get warning messages about the RangedData objects. Should the possible error from the deprecated IRanges be fixed now, or do you think that it's what's causing the error message?

**Comment by akdess** [comment]
Hi @Josephinedh and @dstueckm, 
The new release should resolve those issues.
